### ISSUE TITLE
Clone repo url error

### ISSUE THREAD

**Issue by frigidBlade7** [googlecodelabs/motionlayout#5]
Clone url currently reads 
$ git clone git@github.com:googlecodelabs/motionlayout.git which obviously fails lol
I think it should be 
$ git clone https://github.com/googlecodelabs/motionlayout.git
which actually works for me
Thanks!
<img width="872" alt="Screenshot 2019-07-12 at 20 52 50" src="https://user-images.githubusercontent.com/32777077/61158388-46e08d00-a4e8-11e9-8891-fc4e7ef93779.png">

**Comment by ggfan** [comment]
that is good point: need to configure [git on github](https://github.com/percursoaleatorio/build-me-the-docs-please/blob/master/docs/source/Using_Git/SetUpSSHForGit.rst) to use ssh way.  https way is easy for downloading ( might need one extra step when uploading though ). 

the codelab now is using https://; so closing this one for now.
