### ISSUE TITLE
Null Object reference

### ISSUE THREAD

**Issue by nknr** [googlecodelabs/motionlayout#8]
java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.constraintlayout.motion.widget.MotionScene.getStartId()' on a null object reference in the step1 and step2

**Comment by ggfan** [comment]
I guess you are executing code before step 4 in the first task; in that sense, the code is not completed hence not ready to run, but it could run at step 4.  

Closing down this one, please re-open if this is not the case.  Thank you again for using the codelab and reporting the issue!
